In [6]:
import pandas as pd

In [24]:
df = pd.read_csv('Employees.csv')
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     111 non-null    int64
 1   FIRST_NAME      111 non-null    object
 2   LAST_NAME       111 non-null    object
 3   EMAIL           111 non-null    object
 4   PHONE_NUMBER    111 non-null    object
 5   HIRE_DATE       111 non-null    object
 6   JOB_ID          111 non-null    object
 7   SALARY          111 non-null    int64
 8   COMMISSION_PCT  35 non-null     float64
 9   MANAGER_ID      110 non-null    float64
 10  DEPARTMENT_ID   110 non-null    float64
dtypes: float64(3), int64(2), object(6)
memory usage: 9.7+ KB

In [26]:
# to check number of null value in each column
df.isnull().sum()

EMPLOYEE_ID        0
FIRST_NAME         0
LAST_NAME          0
EMAIL              0
PHONE_NUMBER       0
HIRE_DATE          0
JOB_ID             0
SALARY             0
COMMISSION_PCT    76
MANAGER_ID         1
DEPARTMENT_ID      1
dtype: int64

In [23]:
#df.dropna() # this is temporory change , but for permanent change always use inplace = True

# dropna(axis = 0(default)/1 , how = 'any'(default)/'all' , inplace = True/False(default))

#how = any  -> any 1 null value it will remove whole column.
#how  = all -> have to be all null value to get removed.
df.drop(inplace = True)

ValueError: Need to specify at least one of 'labels', 'index' or 'columns'

In [18]:
df = df.dropna() # no need to keep inplace here
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
45,145,John,Russell,JRUSSEL,011.44.1344.429268,10/1/2004,SA_MAN,14000,0.4,100.0,80.0
46,146,Karen,Partners,KPARTNER,011.44.1344.467268,1/5/2005,SA_MAN,13500,0.3,100.0,80.0
47,147,Alberto,Errazuriz,AERRAZUR,011.44.1344.429278,3/10/2005,SA_MAN,12000,0.3,100.0,80.0
48,148,Gerald,Cambrault,GCAMBRAU,011.44.1344.619268,10/15/2007,SA_MAN,11000,0.3,100.0,80.0
49,149,Eleni,Zlotkey,EZLOTKEY,011.44.1344.429018,1/29/2008,SA_MAN,10500,0.2,100.0,80.0

In [21]:
''' to drop specific columns

drop(columns = [columns_name])
'''
'''
df = df.drop(columns = ['SALARY','JOB_ID'])
df.head()
'''

"\ndf = df.drop(columns = ['SALARY','JOB_ID'])\ndf.head()\n"