In [1]:
import numpy as np
import pandas as pd

In [7]:
import pandas as pd

data = {
    "Employee": [
        "John", "Alice", "Bob", "David", "Eva",
        "Frank", "Grace", "Henry", "Ivy", "Jack",
     
    ],

    "dates" : [
    "2024/01/15",
    "2024/02/10",
    "2024/03/05",
    "2024/04/18",
    "2024/05/22",
    "2024/06/11",
    "2024/07/29",
    "2024/08/14",
    "2024/09/07",
    "2024/10/25"
],

    "Department": [
        "IT", "HR", "Finance", "IT", "Sales",
        "HR", "Finance", "Sales", "IT", "HR",
      
    ],

    "Region": [
        "East", "West", "North", "South", "East",
        "North", "West", "South", "East", "North",
   
    ],

    "Gender": [
        "M", "F", "M", "M", "F",
        "M", "F", "M", "F", "M",
     
    ],

    "Month": [
        "Jan", "Jan", "Jan", "Feb", "Feb",
        "Feb", "Mar", "Mar", "Mar", "Apr",

    ],

    "Salary": [
        60000, 50000, 70000, 65000, 55000,
        52000, 72000, 58000, 68000, 51000,
       
    ],

    "Bonus": [
        5000, 3000, 6000, 5500, 3500,
        3200, 6500, 3800, 5800, 3100,

    ],

    "Sales": [
        120, 80, 150, 130, 100,
        90, 160, 110, 140, 85,
        
    ],

    "Experience": [
        4, 2, 6, 5, 3,
        2, 7, 4, 5, 1,
       
    ]
}

df = pd.DataFrame(data)
df

,Employee,dates,Department,Region,Gender,Month,Salary,Bonus,Sales,Experience
0,John,2024/01/15,IT,East,M,Jan,60000,5000,120,4
1,Alice,2024/02/10,HR,West,F,Jan,50000,3000,80,2
2,Bob,2024/03/05,Finance,North,M,Jan,70000,6000,150,6
3,David,2024/04/18,IT,South,M,Feb,65000,5500,130,5
4,Eva,2024/05/22,Sales,East,F,Feb,55000,3500,100,3
5,Frank,2024/06/11,HR,North,M,Feb,52000,3200,90,2
6,Grace,2024/07/29,Finance,West,F,Mar,72000,6500,160,7
7,Henry,2024/08/14,Sales,South,M,Mar,58000,3800,110,4
8,Ivy,2024/09/07,IT,East,F,Mar,68000,5800,140,5
9,Jack,2024/10/25,HR,North,M,Apr,51000,3100,85,1

In [12]:
pd.pivot_table(df, index="Department", values="Gender", columns="Region", aggfunc='count')

Region      East  North  South  West
Department
Finance      NaN    1.0    NaN   1.0
HR           NaN    2.0    NaN   1.0
IT           2.0    NaN    1.0   NaN
Sales        1.0    NaN    1.0   NaN